### ISSUE TITLE
Trying to serialize a term may have found a bug 

### ISSUE THREAD

**Issue by binarytemple** [tomas-abrahamsson/py_interface#1]
Hi, 
I'm trying to generate the equivalent of the following Erlang data structure, convert to bytes and feed into the sha1 function.

```
erlang:term_to_binary({{<<"fodddo">>,<<"foo">>},<<"bar">>} ).
```

While attempting to construct it in Python I got to this point and could get no further.

```
In [45]: erl_term.ErlTuple( ( erl_term.ErlBinary("foo"  ) ))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-45-58ffc74dc16e> in <module>()
----> 1 erl_term.ErlTuple( ( erl_term.ErlBinary("foo"  ) ))

/usr/local/lib/python2.7/site-packages/py_interface/erl_term.pyc in ErlTuple(elementsAsList)
    157 def ErlTuple(elementsAsList):
    158     """An Erlang tuple. This maps to a python tuple."""
--> 159     return tuple(elementsAsList)
    160
    161 def ErlList(elements):

TypeError: iteration over non-sequence

```

Is this coding error, or a bug ?

**Comment by binarytemple** [comment]
I see that the following works:

``` python
In [67]: bt= erl_term.ErlBinary("fodddo")

In [68]: b = erl_term.ErlBinary("foo")

In [69]: k = erl_term.ErlBinary("bar")

In [70]: erl_term.TermToBinary  (   erl_term.ErlTuple( (bt,b,k) )  )
Out[70]: '\x83h\x03m\x00\x00\x00\x06fodddom\x00\x00\x00\x03foom\x00\x00\x00\x03bar'
```

So the exception only occurs when trying to perform the equivalent of:

``` erlang
term_to_binary({<<"oo">>})
```

**Comment by tomas-abrahamsson** [comment]
Hi, I'm very sorry for taking such enormously long time to respond. I don't know it happened, but I simply missed your question, and discovered it now. I guess by now you probably do not need an answer any more, so this is mostly in case anyone in the future would be helped by it.

The `erl_term.ErlTuple` function was mostly an internal helper. In hindsight, it should have been named `erl_term._ErlTuple` or something similar, to indicate this. The distinction between what was external api and internal helpers in `erl_term` was not very clear, to say the least, so I've added a section on type mapping, between Erlang and Python, to the README.

I'm closing this issue, just re-open should there be anything more.

**Comment by binarytemple** [comment]
Thanks Tomas
